#!/usr/bin/env bash

RUNUSER="sudo -u $(logname)"
$RUNUSER bash ./scripts/updater --autoupdater

line=$(pgrep -u $SUDO_USER hl2_linux)
arr=($line)
inst=$1
if [ $# == 0 ]; then
  inst=0
fi

if [ ${#arr[@]} == 0 ]; then
  echo TF2 isn\'t running!
  exit
fi

if [ $inst -gt ${#arr[@]} ] || [ $inst == ${#arr[@]} ]; then
  echo wrong index!
  exit
fi

proc=${arr[$inst]}

echo Running instances: "${arr[@]}"
echo Attaching to "$proc"

#sudo ./detach $inst bin/libcathook.so

#if grep -q "$(realpath bin/libcathook.so)" /proc/"$proc"/maps; then
#  echo already loaded
#  exit
#fi

# pBypass for crash dumps being sent
# You may also want to consider using -nobreakpad in your launch options.
sudo mkdir -p /tmp/dumps # Make it as root if it doesnt exist
sudo chown root:root /tmp/dumps # Claim it as root
sudo chmod 000 /tmp/dumps # No permissions

FILENAME="/tmp/.gl$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 6)"

cp "bin/libcathook.so" "$FILENAME"

echo loading "$FILENAME" to "$proc"

gdb -n -q -batch \
  -ex "attach $proc" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$FILENAME\", 1)" \
  -ex "call dlerror()" \
  -ex 'print (char *) $2' \
  -ex "continue" \
  -ex "backtrace"

rm $FILENAME
