#!/usr/bin/env bash

if [ $EUID == 0 ]; then
    echo "This script must not be run as root"
    exit
fi

#
# Install base Dependencies
#
if [ -x "$(command -v pacman)" ]; then
    sudo pacman -S --needed --noconfirm git boost cmake make gcc gdb lib32-sdl2 lib32-glew lib32-freetype2 rsync lib32-libglvnd
elif [ -x "$(command -v apt)" ]; then
    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt update
    sudo apt install build-essential git gcc-multilib g++-multilib software-properties-common gcc-snapshot g++-7-multilib gcc-7 g++-7 libboost-all-dev libc6-dev:i386 gdb libsdl2-dev libglew-dev:i386 libglew-dev libfreetype6-dev libfreetype6-dev:i386 cmake gcc-multilib g++-multilib -y
else
    echo -e "\033[1;31m\nCathook autoinstall is not supported on this system! Please install the following packages before continuing: Git, 32 Bit Boost + Headers, CMake, Gcc with 32 bit support, Gdb, 32 Bit SDL + Headers, 32 Bit Glew + Headers, 32 Bit Freetype 2 + Headers, Rsync, 32 Bit libglvnd\n\033[0m"
    read -p "Press enter to continue or CTRL+C to cancel."
fi

#
# Update cathook
#
if [ ! -d "./.git" ]; then
    git init
    git remote add origin https://github.com/nullworks/cathook
fi

git fetch --force --depth 1 origin refs/tags/latest:refs/tags/latest && git reset --hard latest # pull changes from github
git submodule update --depth 1 --init --recursive # update/init submodules

#
# Set config version for update script
#

. ./scripts/config.shlib
cfg_write ./scripts/updater-preferences version 1

#
# Build cathook
#

mkdir -p ./build; pushd build #create a directory for building cathook
cmake ..;make -j$(grep -c '^processor' /proc/cpuinfo) # create makefile and build using all available threads
sudo make data # create /opt/cathook/data
popd; cd ..
