#!/usr/bin/env bash

[[ ! -z "$SUDO_USER" ]] && user=$SUDO_USER || user=$LOGNAME
if ! [ -d "/opt/cathook/data" ]; then
    echo "Creating cathook data directory at /opt/cathook/data"
    mkdir -p "/opt/cathook/data"
    chown -R $user "/opt/cathook/data"
    chmod -R 777 "/opt/cathook/data"
fi

echo "Installing cathook data to /opt/cathook/data"
rsync -avh "data/" "/opt/cathook/data"
rsync -avh --ignore-existing "config_data/" "/opt/cathook/data"
chown -R $user "/opt/cathook/data"
chmod -R 777 "/opt/cathook/data"
