#!/usr/bin/env bash

echo "Searching for Team Fortress 2"
echo "Please wait..."

find / -type d -name "Team Fortress 2" 2>/dev/null | while read path; do
	if [ -e "$path/tf/gameinfo.txt" ]; then
		if grep -q 440 "$path/tf/gameinfo.txt"; then
			echo "Found Team Fortress 2 installation at $path"
			mkdir -p "$path/cathook"
			ln -s "$path/cathook" "Data Folder"
			rsync -avh --progress tf-settings/ "$path/cathook"
			echo "Symbolic link created (Data Folder)"
			echo "You can close this window"
			read -p "Press ENTER to continue"
		fi
	fi
done