#!/usr/bin/env bash
sudo echo Elevated
#Get updated source code
git fetch;git pull origin;git submodule update --remote --recursive
#Update dependencies
cd ./libglez/build; cmake ..; make;sudo make install;cd ..; cd ..
cd ./libxoverlay/build; cmake ..; make;sudo make install;cd ..; cd ..
cd ./simple-ipc/build; cmake ..; make;sudo make install;cd ..; cd ..
#Update cathook
cd build; cmake ..; make; cd ..; cd ..
printf "\n\n";printf '\e[1;34m%-6s\e' "Cathook update complete!";printf "\n\n"