#!/usr/bin/env bash
if [ ! -f ./scripts/updater-preferences ]; then
    while true; do
        read -p "Do you want to enable the cathook auto updater? y/n " yn
        case $yn in
            [Yy]* ) echo true > ./scripts/updater-preferences; break;;
            [Nn]* ) echo false > ./scripts/updater-preferences; exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi
if [ `cat ./scripts/updater-preferences` == "true" ]; then
    ./scripts/run-updater &
fi
