#!/usr/bin/env bash

LOCKFILE=/tmp/chupdater.lock
if [ -e ${LOCKFILE} ] && kill -0 `cat ${LOCKFILE}` >/dev/null; then
    echo -e "\033[1;31m \n \nAuto Updater: Auto Updater already running in the background\n\033[0m"
    exit
fi

# make sure the lockfile is removed when we exit and then claim it
trap "rm -f ${LOCKFILE}; exit" INT TERM EXIT
echo $$ > ${LOCKFILE}

echo -e "\033[1;34 \n \nAuto Updater: Updating cathook in the background\n\033[0m"

sudo -u $(logname) bash -c 'git fetch && git pull origin >/dev/null && git submodule update --init --recursive' || { echo -e "\033[1;31m \n \nAuto Updater: Failed to pull from github!\n\033[0m"; exit 1; }

pushd build >/dev/null || exit 1

sudo cmake --build . --target data >/dev/null || { echo -e "\033[1;31m \n \nAuto Updater:Failed to update /opt/cathook/data directory\n\033[0m"; exit 1; }

sudo -u $(logname) bash -c  'cmake .. >/dev/null && nice -n 10 cmake --build . --target cathook >/dev/null' || { echo -e "\033[1;31m \n \nAuto Updater: Failed to compile cathook\n\033[0m"; exit 1; }

rm -f ${LOCKFILE}

popd >/dev/null

echo -e "\n\n\033[1;34mAuto Updater: Cathook updated successfully\033[0m" && exit 0
