#!/usr/bin/env bash

arch_packages=(git boost cmake make gcc gdb lib32-sdl2 lib32-glew lib32-freetype2 rsync lib32-libglvnd dialog)
ubuntu_packages=(software-properties-common build-essential git g++ g++-multilib libboost-all-dev gdb libsdl2-dev:i386 libglew-dev:i386 libfreetype6-dev:i386 cmake dialog rsync)
fedora_packages=(cmake dialog make g++ glibc-devel.i686 libstdc++-devel.i686 freetype-devel.i686 SDL2-devel.i686 glew-devel.i686 boost-devel.i686 rsync gdb git)

function requestPermissions {
    string=$@
    # Prefer GUI question
    if [ -x "$(command -v zenity)" ] && xset q &>/dev/null; then
        zenity --no-wrap --question --text="Do you want to install the following packages required for cathook?\n${string}?"
        out=$?
        if [ "$out" != 0 ]; then
            exit
        fi
        # Fall back to terminal
    elif [ -t 0 ]; then
        read -p "Do you want to install the following packages required for cathook? ${string} y/n " -r
        if ! [[ $REPLY =~ ^[Yy]$ ]]
        then
            exit
        fi
    else
        echo -e "\033[1;33m\nWarning! Automatic package installation is not supported! Zenity+XOrg or interactive terminal required!\n\033[0m"
        exit
    fi
}

# Determine distro
OSR="$(awk -F= '$1=="ID" { print $2 ;}' /etc/os-release)"
if [[ ("$OSR" == "manjaro" || "$OSR" == "arch") && -x "$(command -v pacman)" ]]; then
    OS="arch"
elif [ "$OSR" == "ubuntu" ] && [ -x "$(command -v apt-get)" ]; then
    OS="ubuntu"
elif [ "$OSR" == "fedora" ] && [ -x "$(command -v dnf)" ] && [ -x "$(command -v rpm)" ]; then
    OS="fedora"
elif [ -x "$(command -v pacman)" ]; then
    OS="arch"
elif [ -x "$(command -v apt-get)" ]; then
    OS="ubuntu"
elif [ -x "$(command -v dnf)" ] && [ -x "$(command -v rpm)" ]; then
    OS="fedora"
fi

if [ "$OS" == "arch" ]; then
    pacman -Qi "${arch_packages[@]}" > /dev/null 2>&1
    out=$?
    if [ "$out" == 1 ]; then
        requestPermissions "${arch_packages[@]}"
        sudo pacman -S --noconfirm --needed "${arch_packages[@]}"
    fi
elif [ "$OS" == "ubuntu" ]; then
    dpkg -s "${ubuntu_packages[@]}" > /dev/null 2>&1
    out=$?
    if [ "$out" == 1 ]; then
        requestPermissions "${ubuntu_packages[@]}"
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y "${ubuntu_packages[@]}"
    fi
elif [ "$OS" == "fedora" ]; then
    string=${fedora_packages[@]}
    rpm -q "${string}" > /dev/null 2>&1
    out=$?
    if [ "$out" == 1 ]; then
        requestPermissions "${fedora_packages[@]}"
        sudo dnf install -y "${string}"
    fi
else
    echo -e "\033[1;33m\nWarning! Automatic package installation is not supported!\n\033[0m"
fi
