#!/usr/bin/env bash

# $3 Init

set -e

configfile="./scripts/updater-preferences"
. ./scripts/config.shlib

tui=true
if [ ! -x "$(command -v dialog)" ]; then
    tui=false
    echo -e "\033[1;31mTerminal UI NOT supported! Install \"dialog\"! \033[0m"
fi
if [ ! -t 0 ]; then
    tui=false
fi

#
# Init goes here
#

if [ "$3" == true ]; then
    cfg_write $configfile update_channel stable
    cfg_write $configfile version 3
fi

version="$(cfg_read $configfile version)"


#
# Migrations go here
#

exists=true

if [ "$version" == 1 ] || [ "$version" == 2 ]; then
    cfg_write $configfile version 3
    if [ -d "./build/CMakeFiles/cathook.dir" ]; then
        rm -r ./build/CMakeFiles/cathook.dir
    fi
fi
