#!/usr/bin/env bash

set -e

configfile="./scripts/updater-preferences"
. ./scripts/config.shlib

# Migrate pre config lib configs
exists=true
cfg_haskey $configfile version || exists=false
if [ "$exists" == false ]; then
    if [ -f $configfile ]; then
        value=$(cat $configfile)
        rm $configfile
    fi  
    echo "" > $configfile
    cfg_write $configfile version 1
    if [ "$(git rev-parse --is-shallow-repository)" == "true" ]; then
        cfg_write $configfile update_channel stable
    else
        cfg_write $configfile update_channel developer
    fi
    if [ -f $configfile ]; then
        if [ "$value" == true ] || [ "$value" == false ]; then 
            cfg_write $configfile autoupdater $value
        fi
    fi
fi

version="$(cfg_read $configfile version)"

tui=true
if [ ! -x "$(command -v dialog)" ]; then
    tui=false
    echo -e "\033[1;31mTerminal UI NOT supported! Install \"dialog\"! \033[0m"
fi
if [ ! -t 0 ]; then
    tui=false
fi

#
# Migrations go here
#

exists=true
cfg_haskey $configfile update_channel || exists=false
if [ "$exists" == false ]; then
    cfg_write $configfile update_channel stable
fi
